<?php
declare(strict_types=1);
session_start();
function db(): PDO { static $db; if (!$db) { $db = new PDO(getenv('DATABASE_URL'), getenv('DB_USER'), getenv('DB_PASSWORD'), [PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]); $db->exec(file_get_contents('/var/www/sql/schema.sql')); if (!(int)$db->query('SELECT count(*) FROM users')->fetchColumn()) { $q=$db->prepare('INSERT INTO users(id,name,password_hash,role) VALUES(?,?,?,?)');$q->execute([uuid(),'admin',password_hash('change-me-now',PASSWORD_DEFAULT),'admin']); } } return $db; }
function uuid(): string { $x=bin2hex(random_bytes(16));return substr($x,0,8).'-'.substr($x,8,4).'-4'.substr($x,13,3).'-'.dechex((hexdec($x[16])&3)|8).substr($x,17,3).'-'.substr($x,20); }
function query(string $sql,array $args=[]): PDOStatement { $q=db()->prepare($sql);$q->execute($args);return $q; }
function h($v): string { return htmlspecialchars((string)($v??''),ENT_QUOTES,'UTF-8'); }
function go(string $p): never { header('Location: /?p='.$p);exit; }
function csrf(): string { return '<input type="hidden" name="csrf" value="'.h($_SESSION['csrf']).'">'; }
function role(...$roles): bool { return in_array($_SESSION['user']['role']??'', $roles,true); }
function event(): ?array { return query('SELECT * FROM events WHERE active=true ORDER BY name LIMIT 1')->fetch(PDO::FETCH_ASSOC)?:null; }
function field(array $d,string $k): string {return h($d[$k]??'');}
function page(string $title): void { echo '<!doctype html><html lang="en"><meta name="viewport" content="width=device-width, initial-scale=1"><title>'.h($title).' · Scouting</title><link rel="stylesheet" href="/style.css"><header><strong>2370 · Scouting</strong><nav><a href="/?p=home">Dashboard</a><a href="/?p=matches">Matches</a><a href="/?p=teams">Teams</a><a href="/?p=picks">Pick list</a><a href="/?p=admin">Admin</a><a href="/?p=logout">Log out</a></nav></header><main><h1>'.h($title).'</h1>'; if(isset($_SESSION['flash'])) {echo '<aside>'.h($_SESSION['flash']).'</aside>';unset($_SESSION['flash']);} }
function endpage(): void {echo '</main></html>';}
try { db(); } catch(Throwable $e) { http_response_code(503);exit('Database unavailable. Start Docker Compose and try again.'); }
$p=$_GET['p']??'home';
if($p==='logout'){session_destroy();header('Location: /');exit;}
if($_SERVER['REQUEST_METHOD']==='POST') {
 if($p==='login') { $u=query('SELECT * FROM users WHERE name=?',[trim($_POST['name']??'')])->fetch(PDO::FETCH_ASSOC);if($u&&password_verify($_POST['password']??'',$u['password_hash'])) {session_regenerate_id(true);$_SESSION['user']=['id'=>$u['id'],'name'=>$u['name'],'role'=>$u['role'],'position'=>$u['position']];$_SESSION['csrf']=bin2hex(random_bytes(16));go('home');} $_SESSION['flash']='Invalid login';go('login'); }
 if(!isset($_SESSION['user']) || !hash_equals($_SESSION['csrf']??'',$_POST['csrf']??'')){http_response_code(403);exit('Invalid session');}
 $e=event();$uid=$_SESSION['user']['id'];
 if($p==='event'&&role('admin')) {query('UPDATE events SET active=false');query('INSERT INTO events(id,name,event_key,active) VALUES(?,?,?,true) ON CONFLICT(event_key) DO UPDATE SET name=EXCLUDED.name,active=true',[uuid(),trim($_POST['name']),trim($_POST['key'])]);go('admin');}
 if($p==='user'&&role('admin')) {if(strlen($_POST['password']??'')<10) {$_SESSION['flash']='Password must be at least 10 characters';go('admin');}query('INSERT INTO users(id,name,password_hash,role,position) VALUES(?,?,?,?,?)',[uuid(),trim($_POST['name']),password_hash($_POST['password'],PASSWORD_DEFAULT),$_POST['role'],$_POST['position']?:null]);go('admin');}
 if($p==='import'&&role('admin')&&$e) { $f=fopen($_FILES['csv']['tmp_name'],'r');$head=array_map('strtolower',fgetcsv($f));$n=0;while(($row=fgetcsv($f))!==false){$r=array_combine($head,$row);$m=(int)($r['match']??0);if(!$m)continue;$mid=query('INSERT INTO matches(id,event_id,match_number) VALUES(?,?,?) ON CONFLICT(event_id,match_number) DO UPDATE SET match_number=EXCLUDED.match_number RETURNING id',[uuid(),$e['id'],$m])->fetchColumn();foreach(['R1','R2','R3','B1','B2','B3'] as $pos){$num=(int)($r[strtolower($pos)]??0);if(!$num)continue;query('INSERT INTO teams(event_id,number) VALUES(?,?) ON CONFLICT DO NOTHING',[$e['id'],$num]);query('INSERT INTO slots(id,match_id,position,team_number) VALUES(?,?,?,?) ON CONFLICT(match_id,position) DO UPDATE SET team_number=EXCLUDED.team_number WHERE NOT EXISTS(SELECT 1 FROM scouting WHERE slot_id=slots.id AND status=\'submitted\')',[uuid(),$mid,$pos,$num]);}$n++;}fclose($f);$_SESSION['flash']="Imported $n matches";go('matches'); }
 if($p==='scout'&&$e) { $slot=query('SELECT s.*,m.event_id FROM slots s JOIN matches m ON m.id=s.match_id WHERE s.id=?',[$_POST['slot']??''])->fetch(PDO::FETCH_ASSOC);if(!$slot||$slot['event_id']!==$e['id']) {http_response_code(404);exit;} $old=query('SELECT * FROM scouting WHERE slot_id=?',[$slot['id']])->fetch(PDO::FETCH_ASSOC);if($old&&$old['status']==='submitted'&&!role('admin','mentor')){http_response_code(403);exit('Submitted record is locked');}if($old&&(int)$old['version']!==(int)($_POST['version']??0)){http_response_code(409);exit('This record changed. Reload before saving.');} $data=[];foreach(['auto_score','teleop_score','endgame','defense','penalties','breakdown','notes'] as $k)$data[$k]=trim((string)($_POST[$k]??''));$status=isset($_POST['submit'])?'submitted':'draft';$id=$old['id']??uuid();$prior=$old['data']??null;query('INSERT INTO scouting(id,slot_id,scout_id,data,status) VALUES(?,?,?,?,?) ON CONFLICT(slot_id) DO UPDATE SET data=EXCLUDED.data,status=EXCLUDED.status,scout_id=EXCLUDED.scout_id,updated_at=now(),version=scouting.version+1,sync_state=\'pending\' ',[$id,$slot['id'],$uid,json_encode($data),$status]);query('INSERT INTO audit(id,record_type,record_id,actor_id,prior_data,new_data) VALUES(?,?,?,?,?,?)',[uuid(),'scouting',$id,$uid,$prior,json_encode($data)]);query('UPDATE slots SET status=? WHERE id=?',[$status,$slot['id']]);go('matches'); }
 if($p==='pit'&&$e) { $num=(int)($_POST['team']??0);if($num<1)exit('Invalid team');$data=[];foreach(['robot','drivetrain','dimensions','weight','mechanisms','scoring','autonomous','endgame','strategy','reliability','requirements','notes'] as $k)$data[$k]=trim((string)($_POST[$k]??''));query('INSERT INTO teams(event_id,number) VALUES(?,?) ON CONFLICT DO NOTHING',[$e['id'],$num]);$old=query('SELECT * FROM pit WHERE event_id=? AND team_number=?',[$e['id'],$num])->fetch(PDO::FETCH_ASSOC);$id=$old['id']??uuid();query('INSERT INTO pit(id,event_id,team_number,author_id,data) VALUES(?,?,?,?,?) ON CONFLICT(event_id,team_number) DO UPDATE SET data=EXCLUDED.data,author_id=EXCLUDED.author_id,updated_at=now(),sync_state=\'pending\' ',[$id,$e['id'],$num,$uid,json_encode($data)]);query('INSERT INTO audit(id,record_type,record_id,actor_id,prior_data,new_data) VALUES(?,?,?,?,?,?)',[uuid(),'pit',$id,$uid,$old['data']??null,json_encode($data)]);go('team&n='.$num); }
 if($p==='pick'&&$e&&role('admin','mentor','drive')) { $num=(int)$_POST['team'];query('INSERT INTO picklist(event_id,team_number,rank,note,do_not_pick) VALUES(?,?,?,?,?) ON CONFLICT(event_id,team_number) DO UPDATE SET rank=EXCLUDED.rank,note=EXCLUDED.note,do_not_pick=EXCLUDED.do_not_pick',[$e['id'],$num,(int)$_POST['rank'],trim($_POST['note']??''),isset($_POST['dnp'])?'true':'false']);go('picks'); }
 http_response_code(403);exit('Forbidden');
}
if(!isset($_SESSION['user'])) {echo '<link rel="stylesheet" href="/style.css"><main><h1>Scouting sign in</h1><form method="post" action="/?p=login"><label>Username<input name="name" required autofocus></label><label>Password<input name="password" type="password" required></label><button>Sign in</button></form><p>First run: admin / change-me-now. Change this password before use.</p></main>';exit;}
$e=event();
if($p==='home'){page('Event dashboard');echo '<p>'.h($e['name']??'No event selected').'</p><aside class="warn">Cloud sync is not configured. Local entries remain in PostgreSQL; remote backup is not active.</aside>';if($e){$x=query('SELECT count(*) FROM slots s JOIN matches m ON m.id=s.match_id WHERE m.event_id=? AND s.status=\'submitted\' ',[$e['id']])->fetchColumn();$t=query('SELECT count(*) FROM slots s JOIN matches m ON m.id=s.match_id WHERE m.event_id=?',[$e['id']])->fetchColumn();echo '<div class="cards"><section><h2>'.h($x).' / '.h($t).'</h2>Completed positions</section><section><h2>'.h($t-$x).'</h2>Remaining</section></div>';echo '<p><a class="button" href="/?p=matches">Open match schedule</a> <a class="button" href="/?p=teams">Browse teams</a></p>';}endpage();}
elseif($p==='admin'){if(!role('admin')){http_response_code(403);exit('Admins only');}page('Administration');echo '<div class="cards"><section><h2>Event</h2><form method="post" action="/?p=event">'.csrf().'<label>Name<input name="name" required placeholder="2026 Vermont Regional"></label><label>Event key<input name="key" required placeholder="2026vtbur"></label><button>Set active event</button></form></section><section><h2>Add user</h2><form method="post" action="/?p=user">'.csrf().'<label>Username<input name="name" required></label><label>Password<input type="password" name="password" minlength="10" required></label><label>Role<select name="role"><option>scout</option><option>pit</option><option>drive</option><option>mentor</option><option>admin</option></select></label><label>Position<select name="position"><option value="">None</option>';foreach(['R1','R2','R3','B1','B2','B3'] as $x)echo '<option>'.h($x).'</option>';echo '</select></label><button>Create account</button></form></section></div>';if($e)echo '<section><h2>Import schedule</h2><p>CSV columns: match,r1,r2,r3,b1,b2,b3. Existing submitted slots are protected.</p><form method="post" action="/?p=import" enctype="multipart/form-data">'.csrf().'<input type="file" name="csv" accept=".csv" required><button>Import CSV</button></form></section>';echo '<h2>Users</h2>';foreach(query('SELECT name,role,position FROM users ORDER BY name')->fetchAll(PDO::FETCH_ASSOC) as $u)echo '<p>'.h($u['name']).' · '.h($u['role']).' '.h($u['position']).'</p>';endpage();}
elseif($p==='matches'){page('Match schedule');if($e){echo '<div class="scroll"><table><thead><tr><th>Match</th>';foreach(['R1','R2','R3','B1','B2','B3'] as $pos)echo '<th>'.h($pos).'</th>';echo '</tr></thead><tbody>';foreach(query('SELECT * FROM matches WHERE event_id=? ORDER BY match_number',[$e['id']]) as $m){echo '<tr><th>Q'.h($m['match_number']).'</th>';foreach(['R1','R2','R3','B1','B2','B3'] as $pos){$s=query('SELECT * FROM slots WHERE match_id=? AND position=?',[$m['id'],$pos])->fetch(PDO::FETCH_ASSOC);echo '<td>'.($s?'<a href="/?p=scout&id='.h($s['id']).'">'.h($s['team_number']).'</a><small>'.h($s['status']).'</small>':'—').'</td>';}echo '</tr>';}echo '</tbody></table></div>';}endpage();}
elseif($p==='scout'){ $s=query('SELECT s.*,m.match_number,m.event_id,m.video_url,sc.data,sc.version,sc.status AS record_status FROM slots s JOIN matches m ON m.id=s.match_id LEFT JOIN scouting sc ON sc.slot_id=s.id WHERE s.id=?',[$_GET['id']??''])->fetch(PDO::FETCH_ASSOC);if(!$s||!$e||$s['event_id']!==$e['id']){http_response_code(404);exit('Slot not found');}$d=json_decode($s['data']??'{}',true);page('Q'.$s['match_number'].' · '.$s['position'].' · Team '.$s['team_number']);if($s['video_url'])echo '<p><a href="'.h($s['video_url']).'">Watch match video</a></p>';if($s['record_status']==='submitted'&&!role('admin','mentor')){echo '<p>Submitted and locked. Ask a mentor to correct this record.</p>';foreach($d as $k=>$v)echo '<p><b>'.h($k).':</b> '.h($v).'</p>';}else{echo '<form method="post" action="/?p=scout">'.csrf().'<input type="hidden" name="slot" value="'.h($s['id']).'"><input type="hidden" name="version" value="'.h($s['version']??0).'">';foreach(['auto_score'=>'Autonomous notes / count','teleop_score'=>'Teleop notes / count','endgame'=>'Endgame','defense'=>'Defense','penalties'=>'Penalties','breakdown'=>'Breakdown / reliability','notes'=>'Observations'] as $k=>$label)echo '<label>'.h($label).'<textarea name="'.h($k).'">'.field($d,$k).'</textarea></label>';echo '<button>Save draft</button> <button name="submit" value="1">Submit</button></form>';}endpage();}
elseif($p==='teams'){page('Teams');if($e)foreach(query('SELECT t.number,t.name,count(sc.id) AS reports FROM teams t LEFT JOIN slots s ON s.team_number=t.number LEFT JOIN matches m ON m.id=s.match_id AND m.event_id=t.event_id LEFT JOIN scouting sc ON sc.slot_id=s.id AND sc.status=\'submitted\' WHERE t.event_id=? GROUP BY t.number,t.name ORDER BY t.number',[$e['id']]) as $t)echo '<p><a href="/?p=team&n='.h($t['number']).'">Team '.h($t['number']).' '.h($t['name']).'</a> · '.h($t['reports']).' reports</p>';endpage();}
elseif($p==='team'||$p==='pit'){ $n=(int)($_GET['n']??0);if(!$e||!$n)go('teams');$record=query('SELECT * FROM pit WHERE event_id=? AND team_number=?',[$e['id'],$n])->fetch(PDO::FETCH_ASSOC);$d=json_decode($record['data']??'{}',true);page('Team '.$n);echo '<h2>Pit scouting</h2><form method="post" action="/?p=pit">'.csrf().'<input type="hidden" name="team" value="'.h($n).'">';foreach(['robot'=>'Robot identity','drivetrain'=>'Drivetrain','dimensions'=>'Dimensions','weight'=>'Weight','mechanisms'=>'Mechanisms','scoring'=>'Scoring capabilities','autonomous'=>'Autonomous','endgame'=>'Endgame','strategy'=>'Preferred strategy','reliability'=>'Reliability','requirements'=>'Special requirements','notes'=>'Notes'] as $k=>$label)echo '<label>'.h($label).'<textarea name="'.h($k).'">'.field($d,$k).'</textarea></label>';echo '<button>Save pit record</button></form><h2>Match reports</h2>';foreach(query('SELECT m.match_number,s.position,sc.data FROM slots s JOIN matches m ON m.id=s.match_id JOIN scouting sc ON sc.slot_id=s.id WHERE m.event_id=? AND s.team_number=? AND sc.status=\'submitted\' ORDER BY m.match_number',[$e['id'],$n]) as $r){$v=json_decode($r['data'],true);echo '<section><b>Q'.h($r['match_number']).' '.h($r['position']).'</b><p>'.h($v['notes']??'').'</p></section>';}endpage();}
elseif($p==='picks'){page('Alliance pick list');if($e){foreach(query('SELECT p.*,t.name FROM picklist p JOIN teams t ON t.event_id=p.event_id AND t.number=p.team_number WHERE p.event_id=? ORDER BY p.rank,p.team_number',[$e['id']]) as $x)echo '<section><b>Pick '.h($x['rank']).' · Team '.h($x['team_number']).'</b> '.($x['do_not_pick']?'⛔ Do not pick':'').'<p>'.h($x['note']).'</p></section>';if(role('admin','mentor','drive')){echo '<h2>Add or update pick</h2><form method="post" action="/?p=pick">'.csrf().'<label>Team<select name="team">';foreach(query('SELECT number FROM teams WHERE event_id=? ORDER BY number',[$e['id']]) as $t)echo '<option>'.h($t['number']).'</option>';echo '</select></label><label>Desired pick number<input name="rank" type="number" min="1" required></label><label>Note<input name="note"></label><label><input type="checkbox" name="dnp"> Do not pick</label><button>Save</button></form>';}}endpage();}
else go('home');
