CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY, name text NOT NULL, password_hash text NOT NULL, role text NOT NULL CHECK(role IN ('admin','mentor','scout','pit','drive')), position text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS events (id uuid PRIMARY KEY, name text NOT NULL, event_key text UNIQUE, active boolean DEFAULT true);
CREATE TABLE IF NOT EXISTS teams (event_id uuid REFERENCES events(id), number integer, name text NOT NULL DEFAULT '', PRIMARY KEY(event_id,number));
CREATE TABLE IF NOT EXISTS matches (id uuid PRIMARY KEY, event_id uuid REFERENCES events(id), match_number integer NOT NULL, video_url text, stage text NOT NULL DEFAULT 'qualification', label text);
ALTER TABLE matches ADD COLUMN IF NOT EXISTS stage text NOT NULL DEFAULT 'qualification';
ALTER TABLE matches ADD COLUMN IF NOT EXISTS label text;
ALTER TABLE matches DROP CONSTRAINT IF EXISTS matches_event_id_match_number_key;
CREATE UNIQUE INDEX IF NOT EXISTS matches_event_stage_number_idx ON matches(event_id,stage,match_number);
CREATE TABLE IF NOT EXISTS slots (id uuid PRIMARY KEY, match_id uuid REFERENCES matches(id), position text NOT NULL CHECK(position IN ('R1','R2','R3','B1','B2','B3')), team_number integer NOT NULL, assigned_user uuid REFERENCES users(id), status text NOT NULL DEFAULT 'unassigned', UNIQUE(match_id,position));
CREATE TABLE IF NOT EXISTS scouting (id uuid PRIMARY KEY, slot_id uuid UNIQUE REFERENCES slots(id), scout_id uuid REFERENCES users(id), data jsonb NOT NULL DEFAULT '{}', status text NOT NULL DEFAULT 'draft', version integer NOT NULL DEFAULT 1, updated_at timestamptz DEFAULT now(), sync_state text NOT NULL DEFAULT 'pending');
CREATE TABLE IF NOT EXISTS pit (id uuid PRIMARY KEY, event_id uuid REFERENCES events(id), team_number integer NOT NULL, author_id uuid REFERENCES users(id), data jsonb NOT NULL DEFAULT '{}', updated_at timestamptz DEFAULT now(), sync_state text NOT NULL DEFAULT 'pending', UNIQUE(event_id,team_number));
CREATE TABLE IF NOT EXISTS audit (id uuid PRIMARY KEY, record_type text NOT NULL, record_id uuid NOT NULL, actor_id uuid REFERENCES users(id), prior_data jsonb, new_data jsonb, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS picklist (event_id uuid REFERENCES events(id), team_number integer, rank integer NOT NULL, note text NOT NULL DEFAULT '', do_not_pick boolean DEFAULT false, PRIMARY KEY(event_id,team_number));
ALTER TABLE picklist ADD COLUMN IF NOT EXISTS picked boolean NOT NULL DEFAULT false;
ALTER TABLE picklist ADD COLUMN IF NOT EXISTS bucket text NOT NULL DEFAULT 'B';
UPDATE picklist SET bucket='DNP' WHERE do_not_pick IS TRUE AND bucket<>'DNP';
CREATE TABLE IF NOT EXISTS event_catalog (year integer NOT NULL, code text NOT NULL, name text NOT NULL, location text NOT NULL, state_code text NOT NULL DEFAULT '', fetched_at timestamptz DEFAULT now(), PRIMARY KEY(year,code));
CREATE TABLE IF NOT EXISTS districts (year integer NOT NULL, code text NOT NULL, name text NOT NULL, fetched_at timestamptz DEFAULT now(), PRIMARY KEY(year,code));
CREATE TABLE IF NOT EXISTS district_events (year integer NOT NULL, district_code text NOT NULL, event_code text NOT NULL, PRIMARY KEY(year,district_code,event_code));
CREATE TABLE IF NOT EXISTS team_photos (event_id uuid NOT NULL, team_number integer NOT NULL, mime text NOT NULL, photo_base64 text NOT NULL, uploaded_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(event_id,team_number), FOREIGN KEY(event_id,team_number) REFERENCES teams(event_id,number));
CREATE TABLE IF NOT EXISTS event_field_images (event_id uuid PRIMARY KEY REFERENCES events(id), mime text NOT NULL, photo_base64 text NOT NULL, uploaded_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS strategy_plans (id uuid PRIMARY KEY, event_id uuid NOT NULL REFERENCES events(id), title text NOT NULL, teams jsonb NOT NULL, paths jsonb NOT NULL, notes text NOT NULL DEFAULT '', author_id uuid REFERENCES users(id), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS site_settings (id integer PRIMARY KEY CHECK(id=1), dark_mode boolean NOT NULL DEFAULT false, logo_mime text, logo_base64 text, logo_uploaded_at timestamptz);
INSERT INTO site_settings(id) VALUES(1) ON CONFLICT DO NOTHING;
